### PR TITLE
chore: remove directories creation

### PR DESCRIPTION
**Pull request by ThibaultFy**

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by thbcmlowk — COMMENTED** [review]
Did we test both in local and docker mode?

**Comment by ThibaultFy** [comment]
> Did we test both in local and docker mode?

Yes I did :)

**Review by thbcmlowk — APPROVED** [review]
LGTM, thanks!

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
